### ISSUE TITLE
gzip badge size different from the actual one 

### ISSUE THREAD

**Issue by siyuniu-ms** [nevware21/badgesize#2]
I used bing and set the encodings as gzip
<img width="334" alt="image" src="https://github.com/nevware21/badgesize/assets/123212536/c761aeb7-c6fb-4d7b-ba30-bb7fecc7dc29">
Then get the gzip size from the network bar
<img width="580" alt="image" src="https://github.com/nevware21/badgesize/assets/123212536/a3094aa2-9cab-4efa-93b3-37e96d30899f">
It's different from the size showed when using badgeSize.

**Comment by nev21** [comment]
Ok, looking at the sizes of the actual response that is returned by accessing
https://[js.monitor.azure.com/scripts/b/ai.3.2.1.min.js](https://js.monitor.azure.com/scripts/b/ai.3.2.1.min.js)

Returned reported size (with GZip Encoding Only enabled)

Content Length: 64647
Total Header Length: 701
Total Network Response bytes: 65348

So it appears that the DevTools is reporting the total network bandwidth (65,348) and that when it's converting to Kb it's dividing by 1000 rather than 1024 (1 Kb / 1024 bytes) resulting in the reported 65.3Kb

While the current deployed version of BadgeSize is only reporting the Content Length (64,647) and it is using dividing this by 1024  resulting in 63.13 Kb being reported (if this used 1000 instead it would still not report the same as it would be 64.65 kb (due to rounding up for 2 decimal)

Both of these values are different from the previous values reported by the original img.badgesize.io implementation as it (appears) to have been performing local gzip / brotli compression on the full downloaded content, while we are reporting the actual returned ContentLength using the requested compression type (gzip/br), thus I believe that using the returned content length is a better reported value than local compression.

This does however, mean that if the CDN service returning the response doesn't support the requested compression format that the response is not actually compressed.

I'll do some research on whether we should be dividing by 1024 (binary (base 2)) vs 1000 (decimal (base 10)), I'm a little old-school (apparently) and while I know that hard drives are now reporting Mb / Gb based on the dividing by the decimal value this just feels wrong from a pure information technology perspective.....

To resolve both of these issues 
- only reporting the content length vs full network bytes (incl headers)
- decimal (1000) / base 2 (1024) division of the values 
I might consider adding some additional query string options to allow you to choose, but I'm inclined to leave the defaults as they existing now (only content length and 1024 = 1kb)

**Comment by nev21** [comment]
Ok I've added a couple of additional options to the query string (if) you really want to include the header length and show in decimal format instead of binary. As part of fixing this I also found an edge case based on the size formatting where at the 1000/1024 boundary it may have displayed the wrong postfix -- now also fixed (just waiting to be released)
